/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as PackageIndexRouteImport } from './routes/package/index'
import { Route as OutsourceIndexRouteImport } from './routes/outsource/index'
import { Route as EventIndexRouteImport } from './routes/event/index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment/index'
import { Route as CreateEventIndexRouteImport } from './routes/createEvent/index'
import { Route as CompanyIndexRouteImport } from './routes/company/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIndexRoute = PackageIndexRouteImport.update({
  id: '/package/',
  path: '/package/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutsourceIndexRoute = OutsourceIndexRouteImport.update({
  id: '/outsource/',
  path: '/outsource/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEventIndexRoute = CreateEventIndexRouteImport.update({
  id: '/createEvent/',
  path: '/createEvent/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyIndexRoute
  '/createEvent': typeof CreateEventIndexRoute
  '/equipment': typeof EquipmentIndexRoute
  '/event': typeof EventIndexRoute
  '/outsource': typeof OutsourceIndexRoute
  '/package': typeof PackageIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyIndexRoute
  '/createEvent': typeof CreateEventIndexRoute
  '/equipment': typeof EquipmentIndexRoute
  '/event': typeof EventIndexRoute
  '/outsource': typeof OutsourceIndexRoute
  '/package': typeof PackageIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company/': typeof CompanyIndexRoute
  '/createEvent/': typeof CreateEventIndexRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/event/': typeof EventIndexRoute
  '/outsource/': typeof OutsourceIndexRoute
  '/package/': typeof PackageIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/createEvent'
    | '/equipment'
    | '/event'
    | '/outsource'
    | '/package'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/createEvent'
    | '/equipment'
    | '/event'
    | '/outsource'
    | '/package'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/company/'
    | '/createEvent/'
    | '/equipment/'
    | '/event/'
    | '/outsource/'
    | '/package/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  CreateEventIndexRoute: typeof CreateEventIndexRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
  EventIndexRoute: typeof EventIndexRoute
  OutsourceIndexRoute: typeof OutsourceIndexRoute
  PackageIndexRoute: typeof PackageIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/': {
      id: '/package/'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof PackageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outsource/': {
      id: '/outsource/'
      path: '/outsource'
      fullPath: '/outsource'
      preLoaderRoute: typeof OutsourceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/': {
      id: '/event/'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createEvent/': {
      id: '/createEvent/'
      path: '/createEvent'
      fullPath: '/createEvent'
      preLoaderRoute: typeof CreateEventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  CreateEventIndexRoute: CreateEventIndexRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
  EventIndexRoute: EventIndexRoute,
  OutsourceIndexRoute: OutsourceIndexRoute,
  PackageIndexRoute: PackageIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
